### ISSUE TITLE
As a busy student, I want to know what tasks are important at first glance so that I can manage my time well.

### ISSUE THREAD

**Issue by Clouddoggo** [AY1920S2-CS2103T-F09-2/main#103]
- [x] Implement Priority Class

- [x]  Differentiate Tasks by priority in MainWindow

- [ ] Sort tasks with high priority above tasks with lower priority
