### ISSUE TITLE
More DG Feedback

### ISSUE THREAD

**Issue by ongaaron96** [AY1920S2-CS2103T-F09-2/main#349]
- [x] Figure 2: wrong arrow for implements, same for Figure 5

![image](https://user-images.githubusercontent.com/40322372/78987483-c0350b00-7b60-11ea-945f-262452356638.png)
- [x] Figure 6: would be better if Logic had the same blue colour scheme as the architecture diagrams (now its purple-ish), or change the architecture diagram's Logic colour to this instead; can remove the information tooltip below ("lifeline should end at destroy marker ...")
- [x] Figure 7: is `filteredTasks` a role or label? If its a role, place it in the correct location, if its a label, add the arrow head (sounds like a role); 
![image](https://user-images.githubusercontent.com/40322372/78986118-143df080-7b5d-11ea-97d9-6aac05a40e1f.png)

### Tab system
- [x] Might be better to show a general sequence diagram here to explain this instead:
![image](https://user-images.githubusercontent.com/40322372/78986638-48fe7780-7b5e-11ea-9aa7-c643e2aff51a.png)

### Summary feature
- [x] Figure 10: better to write `populateSummary()` and `isShowSummary()` (with the parentheses) since they are methods; extend the lifelines if they are not deleted else show that they are deleted
- [x] Explain Figure 10 in words before showing it

### Task grouping feature
- [x] Figure 11: remove the empty compartments (you can remove the empty compartment for other classes with no attributes or methods listed):
![image](https://user-images.githubusercontent.com/40322372/78987376-66ccdc00-7b60-11ea-80df-5abdc5d2c22f.png)
- [x] Figure 11: recommended to indicate abstract classes using `{abstract}` instead of italics; if a class is abstract, would be better to show which of its method(s) makes it abstract; wrong arrow for implements
- [x] Figure 12: wrong end node symbol
- [x] Figure 13: arrows are used to show that a method is invoked, if this is not a method remove it:
![image](https://user-images.githubusercontent.com/40322372/78987934-0b9be900-7b62-11ea-88c4-52820bbaa9ac.png)
- [x] Figure 14: too small! compact it and make it bigger

### Calendar feature
- [x] Figure 15: place association labels in the middle of the arrow
- [x] Place Figure 16 under "**Function 1: Displays an overview of tasks in calendar...**". After you describe the 2 commands, explain the internal steps that are taken to execute those commands, then end it off with the Figure 16 SD.
- [x] Then, continue with "**Function 2: Display a list of tasks...**" and explain how `calendar DATE` is different from the above.
- [x] Then you can conclude with Figure 17.
- [x] Figure 16: LogicManager activation bar too long!
- [x] Figure 17: wrong end node symbol

### Productivity feature
- [x] Very little explanations, explain the internal steps taken to execute your commands, before showing the diagrams
- [x] Figure 18 and 19: wrong end node symbol
- [x] Figure 19: something wrong here, if theres a loop maybe a sequence diagram would be better:
![image](https://user-images.githubusercontent.com/40322372/78991873-87029800-7b6c-11ea-996d-df2c69f7e09f.png)
- [x] Figure 20: LogicManager activation bar too long; `parseCommand()` arrow not connected; notation for constructing `StopCommandParser` is wrong:
![image](https://user-images.githubusercontent.com/40322372/78992152-2d4e9d80-7b6d-11ea-994a-6ed0aa204ad5.png)

### Reminder feature
- [x] Figure 24: missing activation bar for self invocation:
![image](https://user-images.githubusercontent.com/40322372/78992759-9c78c180-7b6e-11ea-9eef-20ef5acbc557.png)
- [x] Move your explanations to before Figure 22

### Undo/redo
- [x] Remove this:
![image](https://user-images.githubusercontent.com/40322372/78992845-da75e580-7b6e-11ea-94b0-43e4cbafcc74.png)
- [x] Fix this:
![image](https://user-images.githubusercontent.com/40322372/78992862-e661a780-7b6e-11ea-8534-fd059c6d808d.png)

### Overall
- Recommended flow for implementation:
1. State command/feature and describe what it does
2. Explain briefly the internal steps taken to execute this command
3. Show SD/AD to summarise your exaplanations
- Diagrams are there to complement your explanations and help readers understand your implementations better - dont leave out the explanations!
- Theres quite a number of aggregation symbols used in some class diagrams. If you are 100% sure its an aggregation you can ignore this comment, if not change it to a normal association to be safe
- Some classes / methods not `coded`
- As mentioned in previous feedback: For design considerations, after listing pros and cons, include a short paragraph explaining the reasons for the chosen implementation. Address the cons of the chosen implementation and the pros of the alternatives.
- Overall good improvements since the last feedback! All the best for the final exam!

**Comment by yapdianhao** [comment]
Thanks Aaron ! 🥰
