### ISSUE TITLE
Tasks due for final release

### ISSUE THREAD

**Issue by yaojiethng** [AY1920S2-CS2103T-F09-2/main#355]
### CS2101 ###
- [x] submit UG and DG

### Tasks for UG
- [x]  update all screenshots with latest UI
#### Cleanup before submission
- [x] all tables have a header
- [x] correct symbols and notation
- [x] all figures have a caption
- [x] All class and method names are marked down

#### Implement changes from Aaron's feedback:
- [x] Architecture Components
- [x] Tab system
- [x] Summary feature
- [x] Task grouping feature
- [x] Calendar feature
- [x] Productivity feature
- [x] Reminder feature
- [x] Undo/redo
#### Cleanup before submission
- [x] all tables have a header
- [x] all figures have a caption
- [x] Fill in Effort section
- [x] All class and method names are marked down

### JAR
- [ ] Manage milestone for v1.4 
- [ ] assign all the issues and PR to v1.4 (or for Stuff we nt doing set to 2.0)
- [ ] make a 1.4 release incl jar file
- [ ] test Jar file on linux, windows, mac

### Files requiread for Individual Submission
PPP (Indiv make your pdf and submit)
UML diagrams (Collate all the .png files of diagrams that you made and collate into a pdf and submit)

### Yaojie
- [x] I am done with the code
- [x] I am done with UG changes
- [x] I am done with DG changes
- [x] I have done my PPP
- [x] I have submitted my individual .pdf files for PPP and UML diagrams

### Amanda
- [x] I am done with the code
- [x] I am done with UG changes
- [x] I am done with DG changes
- [x] I have done my PPP
- [x] I have submitted my individual .pdf files for PPP and UML diagrams

### Jel
- [x] I am done with the code
- [x] I am done with UG changes
- [x] I am done with DG changes
- [x] I have done my PPP
- [x] I have submitted my individual .pdf files for PPP and UML diagrams

### Eden
- [x] I am done with the code
- [x] I am done with UG changes
- [x] I am done with DG changes
- [x] I have done my PPP
- [x] I have submitted my individual .pdf files for PPP and UML diagrams

### Dianhao
- [x] I am done with the code
- [x] I am done with UG changes
- [x] I am done with DG changes
- [x] I have done my PPP
- [x] I have submitted my individual .pdf files for PPP and UML diagrams
