### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by alam8064** [AY1920S2-CS2103T-F09-2/main#69]
mid-v1.2
- [x] 1) implement DateTime model class (Completed by @Clouddoggo)
- [x] 2) implement Status model class (Completed by @eedenong)
- [x] 3) implement Priority model class (Completed by @eedenong) 
- [x] 4) implement DoneCommand, DoneCommandParser, DoneCommandTest
- [x] 4) Fix moduleCode class to remove all data from the old email class (Completed by @yaojiethng)
- [x] 5) update addCommand and editCommand to reflect the new model classes (Completed by @yaojiethng, @alam8064)
- [x] 6) edit the json storage so we can store the new classes (Completed by @yapdianhao)
- [x] 7) edit the TaskCard.fxml card to our new planned layout (Completed by @alam8064)
- [x] 8) Resolve all checkstyle conflicts (Completed by @Clouddoggo, @yaojiethng)
- [x] 9) Updated aboutUs, contactUs other .adoc files (Completed by @alam8064) 
- [x] 10) Rewrite affected test classes (Completed by @Clouddoggo, @yaojiethng, @eedenong)

v1.2
- [x] Feature: Set Reminders and Notifications, Colours for prioritising modules (to be done by @yapdianhao)
- [x] Feature: Categorise tasks (by today, week, month) (to be done by @yaojiethng)
- [x] Feature: Integrate Calender on Interface (to be done by @alam8064)
- [x] Feature: Productivity tracker (to be done by @Clouddoggo)
- [x] Feature: Morning call/Night debrief, Sticky notes (to be done by @eedenong)

**Comment by Clouddoggo** [comment]
Productivity tracker: 
v1.2: Set up parser for command to track productivity in a day, show default image for productivity level. 
v1.3: Add options to track productivity in a week/month. Update imagery to be responsive and show the different levels of productivity.

**Comment by Clouddoggo** [comment]
We need to renumber the figures in our UG and list out all the possible datetime formats accepted by Jelphabot before peer review on 26 March.
