### ISSUE TITLE
Feature: Productivity tracker 

### ISSUE THREAD

**Issue by Clouddoggo** [AY1920S2-CS2103T-F09-2/main#89]
Set up parser for command to track productivity in a day.

- [x]  Add stop and start command parser classes and to JelphabotParser
- [x]  Store duration taken for task completion as Task attribute
- [x]  Lock commands for deleting tasks when timer is running.
- [x]  On exit, if timer is not stopped, discard recorded time.
