### ISSUE TITLE
As a student taking multiple modules, I want to label tasks by ModuleCode so that I can manage the time spent on each module.

### ISSUE THREAD

**Issue by Clouddoggo** [AY1920S2-CS2103T-F09-2/main#99]
- [x] Implement moduleCode model class 

- [ ] Color classes of the same module with the same color in MainWindow

- [ ] Allow Find accept module code as an argument

- [ ] (Optional) Productivity tracker can track time spent by module
